name: Node workflow 1
on:
  [workflow_dispatch, pull_request]
   
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest] # ubuntu-22.04
    steps:
      - uses: step-security/harden-runner@int
        with:
          allowed-endpoints: 
           int.api.stepsecurity.io:443
           codecov.io:443
           github.com:443
           nodejs.org:443
           registry.npmjs.org:443
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install

      - name: Prettier Format Check
        run: npm run format-check

      - name: ESLint Check
        run: npm run lint
        
      - name: Send Coverage
        continue-on-error: true
        timeout-minutes: 1
        run: |
          curl -s https://codecov.io/bash | bash -s -- -t ${{secrets.CODECOV_TOKEN}} -f coverage/lcov.info -n github-actions-codecov-${{ matrix.operating-system }}
          curl -X GET https://www.stepsecurity.io
          
      - name: print journalctl
        run: sudo journalctl -k --boot
      
      - name: print systemd-resolve
        run: sudo systemd-resolve --status
        
      - name: print dns cache
        run: |
          sudo killall -USR1 systemd-resolved
          sudo journalctl -u systemd-resolved > ~/dns-cache.txt
          less ~/dns-cache.txt
