name: Node workflow 1
on:
  [workflow_dispatch, pull_request]
   
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest] # ubuntu-22.04
    steps:
      - name: Get sudo file
        run: |
          sudo ls /etc/sudoers.d
